service: [Default service]
app: [Default app]
org: [Default org]

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: [Default region]

functions:
  numpy:
    handler: handler.main
    
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
